import React from 'react';
import { socialLinks } from '../data/sociallinks';



export default function AboutHero() {
  return (
   
    <div className="static box-content caret-black max-w-none outline-black scroll-auto mx-0 p-0 md:relative md:aspect-auto md:box-border md:caret-transparent md:max-w-6xl md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mx-auto md:pt-36 md:pb-20 md:px-4 md:scroll-m-0 md:scroll-p-[auto]">
      <h2 className="static text-2xl font-bold box-content caret-black tracking-[normal] leading-[normal] max-w-none outline-black scroll-auto text-start z-auto md:relative md:text-6xl md:font-medium md:aspect-auto md:box-border md:caret-transparent md:tracking-[-1.5px] md:leading-[60px] md:max-w-lg md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:underline-offset-auto md:z-[2] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <p className="text-black text-base font-normal box-content caret-black tracking-[normal] leading-[normal] outline-black scroll-auto normal-case mb-0 md:text-[oklab(0.999994_0.0000455677_0.0000200868_/_0.7)] md:text-sm md:aspect-auto md:box-border md:caret-transparent md:tracking-[1.4px] md:leading-5 md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:uppercase md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mb-3 md:scroll-m-0 md:scroll-p-[auto]">More About Me</p>
        <span className="box-content caret-black outline-black scroll-auto font-times md:aspect-auto md:box-border md:caret-transparent md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-instrument_serif">
          <span className="box-content caret-black outline-black scroll-auto md:aspect-auto md:box-border md:caret-transparent md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">I'm Aayush, a creative</span>
          <span className="not-italic bg-clip-border bg-none bg-auto box-content caret-black outline-black scroll-auto pr-0 md:italic md:aspect-auto md:bg-clip-text md:bg-[linear-gradient(288deg,rgb(255,128,0),rgb(255,0,204)_53.2394%,rgb(0,68,255))] md:bg-size-[200%_200%] md:box-border md:caret-transparent md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pr-2 md:scroll-m-0 md:scroll-p-[auto]"> engineer</span>
        </span>
      </h2>
       
      <div className="[align-items:normal] box-content caret-black block justify-normal outline-black scroll-auto md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:justify-between md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static text-black text-base font-normal box-content caret-black block flex-row tracking-[normal] leading-[normal] max-w-none min-h-0 min-w-0 outline-black gap-y-[normal] scroll-auto text-start z-auto md:relative md:text-[oklch(0.87_0_0)] md:text-lg md:font-light md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:tracking-[0.9px] md:leading-[28.0001px] md:max-w-[550px] md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-8 md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:underline-offset-auto md:z-[5] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <p className="box-content caret-black min-h-0 min-w-0 outline-black scroll-auto md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            I'm Aayush Bharti, a proactive full-stack developer passionate about creating dynamic web experiences. 
            From frontend to backend, I thrive on solving complex problems with clean, efficient code. 
            My expertise spans React, Next.js, and Node.js, and I'm always eager to learn more.
          </p>
          <p className="box-content caret-black min-h-0 min-w-0 outline-black scroll-auto md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            When I'm not immersed in work, I'm exploring new ideas and staying curious. 
            Life's about balance, and I love embracing every part of it.
          </p>
          <p className="box-content caret-black min-h-0 min-w-0 outline-black scroll-auto md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            I believe in waking up each day eager to make a difference!
          </p>
          
          <div className="box-content caret-black gap-x-[normal] block min-h-0 min-w-0 outline-black gap-y-[normal] scroll-auto w-auto mt-0 md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-fit md:[mask-position:0%] md:bg-left-top md:-mt-4 md:scroll-m-0 md:scroll-p-[auto]">
            {socialLinks.map((link) => (
              <button key={link.id} className="bg-zinc-100 caret-black inline-block min-h-0 min-w-0 outline-black scroll-auto text-center md:aspect-auto md:bg-transparent md:caret-transparent md:block md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:p-0 md:scroll-m-0 md:scroll-p-[auto]">
                <a href={link.href} className="box-content caret-black outline-black scroll-auto md:aspect-auto md:box-border md:caret-transparent md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <span className="static box-content caret-black inline h-auto outline-black scroll-auto text-wrap w-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:block md:h-px md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-px md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:-m-px md:scroll-m-0 md:scroll-p-[auto]">{link.label}</span>
                  <img src={link.icon} alt="Icon" className="box-content caret-black h-auto outline-black scroll-auto w-auto md:aspect-auto md:box-border md:caret-transparent md:h-5 md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
                </a>
              </button>
            ))}
          </div>
        </div>
        
        <div className="static [align-items:normal] box-content caret-black block flex-row h-auto justify-normal max-w-none min-h-0 min-w-0 outline-black scroll-auto w-auto mr-0 md:relative md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:h-[450px] md:justify-center md:max-w-[150px] md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:mr-40 md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static box-content caret-black h-auto min-h-0 min-w-0 outline-black scroll-auto w-auto md:relative md:aspect-auto md:box-border md:caret-transparent md:h-full md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:mr-80">
            <div className="static shadow-none box-content caret-black outline-black scroll-auto transform-none z-auto rounded-none left-auto md:absolute md:aspect-auto md:shadow-[rgba(0,0,0,0.5)_0px_10px_30px_0px] md:box-border md:caret-transparent md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[3] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[30px] md:left-2/4">
              <div className="static box-content caret-black outline-black scroll-auto w-auto md:relative md:aspect-[4_/_5] md:box-border md:caret-transparent md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[300px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <img alt="Coding image" sizes="100vw" src="https://c.animaapp.com/mfku12zuwN9ojj/assets/2.avif" className="static text-black box-content h-auto max-w-none object-fill outline-black scroll-auto w-auto rounded-none inset-auto md:absolute md:text-transparent md:aspect-auto md:box-border md:h-full md:max-w-full md:object-cover md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-3xl md:inset-0" />
              </div>
            </div>
            <div className="static shadow-none box-content caret-black outline-black scroll-auto transform-none z-auto rounded-none left-auto md:absolute md:aspect-auto md:shadow-[rgba(0,0,0,0.5)_0px_10px_30px_0px] md:box-border md:caret-transparent md:brightness-[0.7] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[30px] md:left-[95%]">
              <div className="static box-content caret-black outline-black scroll-auto w-auto md:relative md:aspect-[4_/_5] md:box-border md:caret-transparent md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[300px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <img alt="Travel image" sizes="100vw" src="https://c.animaapp.com/mfku12zuwN9ojj/assets/4.avif" className="static text-black box-content h-auto max-w-none object-fill outline-black scroll-auto w-auto rounded-none inset-auto md:absolute md:text-transparent md:aspect-auto md:box-border md:h-full md:max-w-full md:object-cover md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-3xl md:inset-0" />
              </div>
            </div>
            <div className="static shadow-none box-content caret-black outline-black scroll-auto transform-none z-auto rounded-none left-auto md:absolute md:aspect-auto md:shadow-[rgba(0,0,0,0.5)_0px_10px_30px_0px] md:box-border md:caret-transparent md:brightness-[0.7] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[30px] md:left-[5%]">
              <div className="static box-content caret-black outline-black scroll-auto w-auto md:relative md:aspect-[4_/_5] md:box-border md:caret-transparent md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[300px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <img alt="GYM image" sizes="100vw" src="https://c.animaapp.com/mfku12zuwN9ojj/assets/3.avif" className="static text-black box-content h-auto max-w-none object-fill outline-black scroll-auto w-auto rounded-none inset-auto md:absolute md:text-transparent md:aspect-auto md:box-border md:h-full md:max-w-full md:object-cover md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-3xl md:inset-0" />
              </div>
            </div>
          </div>
          <h3 className="text-[18.72px] font-bold box-content caret-black leading-[normal] min-h-0 min-w-0 outline-black scroll-auto text-start md:text-2xl md:font-light md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:text-center md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">I Code</h3>
        </div>
      </div>
    </div>
  );
}
