import React from 'react';
import { projects, projectTechnologies } from '../data/projectsdata';

export default function ProjectsSection() {
  return (
    <section className="relative box-border caret-transparent max-w-screen-xl outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth w-full mt-28 mx-auto py-10">
      <h2 className="relative text-5xl font-medium box-border caret-transparent tracking-[-1.2px] leading-[48px] outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth text-center z-[2] mb-20 md:text-6xl md:tracking-[-1.5px] md:leading-[60px] md:mb-36">
        <p className="text-[oklab(0.999994_0.0000455677_0.0000200868_/_0.7)] text-xs font-normal box-border caret-transparent tracking-[1.2px] leading-4 outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth uppercase mb-3 md:text-sm md:tracking-[1.4px] md:leading-5">FEATURED CASE STUDIES</p>
        <span className="text-5xl box-border caret-transparent tracking-[-1.2px] leading-[48px] outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth font-instrument_serif md:text-6xl md:tracking-[-1.5px] md:leading-[60px]">
          <span className="text-5xl box-border caret-transparent tracking-[-1.2px] leading-[48px] outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth md:text-6xl md:tracking-[-1.5px] md:leading-[60px]">Curated</span>
          <span className="text-5xl italic bg-clip-text bg-[linear-gradient(288deg,rgb(255,128,0),rgb(255,0,204)_53.2394%,rgb(0,68,255))] bg-size-[200%_200%] box-border caret-transparent tracking-[-1.2px] leading-[48px] outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth pr-2 md:text-6xl md:tracking-[-1.5px] md:leading-[60px]">work</span>
        </span>
      </h2>
      
      <div className="relative box-border caret-transparent flex outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth w-full mx-auto">
        <div className="box-border caret-transparent gap-x-6 grid flex-row grid-cols-[repeat(1,minmax(0px,1fr))] max-w-none outline-[oklab(0.556_0_0_/_0.5)] gap-y-6 scroll-smooth mx-auto md:flex md:flex-col md:grid-cols-[repeat(2,minmax(0px,1fr))] md:max-w-[65%] md:gap-y-24">
          {projects.map((project) => (
            <div key={project.id} className="box-border caret-transparent flex outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth w-full">
              <div className="box-border caret-transparent flex flex-col outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth w-auto mx-0 md:w-full md:mx-10">
                <a href={project.href} className="relative bg-zinc-100/0 shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0.25)_0px_25px_50px_-12px] box-border caret-transparent block h-auto outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth border overflow-hidden p-1.5 rounded-2xl border-solid border-[oklab(0.999994_0.0000455678_0.0000200868_/_0.15)] md:h-[560px] md:p-2 md:rounded-3xl">
                  <div className="absolute bg-[linear-gradient(90deg,rgba(0,0,0,0)_5%,rgba(255,255,255,0.8)_35%,rgb(255,255,255)_50%,rgba(255,255,255,0.8)_65%,rgba(0,0,0,0)_95%)] box-border caret-transparent h-px outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth top-0 inset-x-0"></div>
                  <div className="relative items-center bg-[linear-gradient(oklab(0.144788_7.45058e-9_7.45058e-9_/_0.4)_0px,rgba(0,0,0,0)_100%)] box-border caret-transparent flex flex-col h-full justify-between outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth w-full overflow-hidden rounded-[14px] md:rounded-2xl">
                    <div className="absolute bg-[linear-gradient(188.62deg,rgb(107,13,51)_49.9%,rgb(219,39,119)_81.7%,rgb(244,114,182)_93.88%,rgb(249,215,147)_113.5%)] box-border caret-transparent outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth z-[-1] inset-0"></div>
                    <div className="absolute bg-[linear-gradient(90deg,rgba(0,0,0,0)_20%,rgb(255,255,255)_50%,rgba(0,0,0,0)_80%)] box-border caret-transparent h-[0.8px] opacity-70 outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth z-10 top-px inset-x-0"></div>
                    <div className="text-[oklch(0.823_0.12_346.018)] items-center box-border caret-transparent hidden justify-between min-h-0 min-w-0 outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth w-full px-12 py-8 md:flex md:min-h-[auto] md:min-w-[auto]">
                      <h3 className="text-3xl box-border caret-transparent tracking-[0.75px] leading-9 max-w-[90%] min-h-0 min-w-0 outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth font-instrument_serif md:min-h-[auto] md:min-w-[auto]">{project.description}</h3>
                      <img src={project.iconSrc} alt="Icon" className="box-border caret-transparent h-6 outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth w-6" />
                    </div>
                    <img alt={project.title} src={project.imageSrc} className="text-transparent aspect-[auto_1203_/_753] shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgb(219,39,119)_0px_0px_30px_0px] box-border max-w-[85%] outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth w-full border rounded-t-[10px] border-solid border-[oklab(0.999994_0.0000455678_0.0000200868_/_0.2)]" />
                  </div>
                </a>
              </div>
            </div>
          ))}
        </div>
        
        <div className="static box-content caret-black min-h-0 min-w-0 outline-black scroll-auto w-auto py-0 md:sticky md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[35%] md:[mask-position:0%] md:bg-left-top md:py-4 md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static box-content caret-black outline-black scroll-auto top-auto md:sticky md:aspect-auto md:box-border md:caret-transparent md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:top-40">
            <div className="box-content caret-black block outline-black scroll-auto md:aspect-auto md:box-border md:caret-transparent md:flex md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
              <div className="bg-transparent box-content caret-black h-auto min-h-0 min-w-0 outline-black scroll-auto mr-0 my-0 rounded-none md:aspect-auto md:bg-[oklch(0.488_0.243_264.376)] md:box-border md:caret-transparent md:h-1 md:min-h-[auto] md:min-w-6 md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mr-4 md:my-4 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[3.35544e+07px]"></div>
              <div className="[align-items:normal] box-content caret-black block flex-row h-auto min-h-0 min-w-0 outline-black scroll-auto md:items-start md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:h-[500px] md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="[align-items:normal] box-content caret-black gap-x-[normal] block min-h-0 min-w-0 outline-black gap-y-[normal] scroll-auto md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <h3 className="text-[18.72px] font-bold box-content caret-black leading-[normal] min-h-0 min-w-0 outline-black scroll-auto font-times md:text-3xl md:aspect-auto md:box-border md:caret-transparent md:leading-9 md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-instrument_serif">Personal Portfolio</h3>
                </div>
                <p className="text-black font-normal box-content caret-black min-h-0 min-w-0 outline-black scroll-auto my-0 md:text-[oklch(0.708_0_0)] md:font-light md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:my-2 md:scroll-m-0 md:scroll-p-[auto]">
                  A personal portfolio showcasing modern web design and user experience with sleek layouts, smooth animations, and highlights of my skills and projects.
                </p>
                <ul className="text-black box-content caret-black block flex-row list-disc min-h-0 min-w-0 outline-black gap-y-[normal] scroll-auto mt-0 pl-10 md:text-[oklab(0.985_0_0_/_0.85)] md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:list-none md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-4 md:pl-0 md:scroll-m-0 md:scroll-p-[auto]">
                  <li className="text-base [align-items:normal] box-content caret-black list-item leading-[normal] min-h-0 min-w-0 outline-black scroll-auto text-left md:text-sm md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:leading-5 md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <img src="https://c.animaapp.com/mfbwn9s8eMdF5x/assets/icon-20.svg" alt="Icon" className="text-black bg-transparent box-content caret-black shrink h-auto outline-black scroll-auto w-auto mr-0 mt-0 md:text-[oklch(0.707_0.165_254.624)] md:aspect-auto md:bg-neutral-950 md:box-border md:caret-transparent md:shrink-0 md:h-5 md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-5 md:[mask-position:0%] md:bg-left-top md:mr-2 md:mt-1 md:scroll-m-0 md:scroll-p-[auto]" />
                   Integrated PostgreSQL and Prisma for efficient data handling.
                  </li>
                  <li className="text-base [align-items:normal] box-content caret-black list-item leading-[normal] min-h-0 min-w-0 outline-black scroll-auto text-left md:text-sm md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:leading-5 md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <img src="https://c.animaapp.com/mfbwn9s8eMdF5x/assets/icon-20.svg" alt="Icon" className="text-black bg-transparent box-content caret-black shrink h-auto outline-black scroll-auto w-auto mr-0 mt-0 md:text-[oklch(0.707_0.165_254.624)] md:aspect-auto md:bg-neutral-950 md:box-border md:caret-transparent md:shrink-0 md:h-5 md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-5 md:[mask-position:0%] md:bg-left-top md:mr-2 md:mt-1 md:scroll-m-0 md:scroll-p-[auto]" />
                   Built with Next.js and TypeScript for performance and scalability.
                  </li>
                  <li className="text-base [align-items:normal] box-content caret-black list-item leading-[normal] min-h-0 min-w-0 outline-black scroll-auto text-left md:text-sm md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:leading-5 md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <img src="https://c.animaapp.com/mfbwn9s8eMdF5x/assets/icon-20.svg" alt="Icon" className="text-black bg-transparent box-content caret-black shrink h-auto outline-black scroll-auto w-auto mr-0 mt-0 md:text-[oklch(0.707_0.165_254.624)] md:aspect-auto md:bg-neutral-950 md:box-border md:caret-transparent md:shrink-0 md:h-5 md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-5 md:[mask-position:0%] md:bg-left-top md:mr-2 md:mt-1 md:scroll-m-0 md:scroll-p-[auto]" />
                    Implemented state management with Zustand and validation using Zod.
                  </li>
                  <li className="text-base [align-items:normal] box-content caret-black list-item leading-[normal] min-h-0 min-w-0 outline-black scroll-auto text-left md:text-sm md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:leading-5 md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <img src="https://c.animaapp.com/mfbwn9s8eMdF5x/assets/icon-20.svg" alt="Icon" className="text-black bg-transparent box-content caret-black shrink h-auto outline-black scroll-auto w-auto mr-0 mt-0 md:text-[oklch(0.707_0.165_254.624)] md:aspect-auto md:bg-neutral-950 md:box-border md:caret-transparent md:shrink-0 md:h-5 md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-5 md:[mask-position:0%] md:bg-left-top md:mr-2 md:mt-1 md:scroll-m-0 md:scroll-p-[auto]" />
                    Secured authentication with Auth.js for user account management.
                  </li>                 
                </ul>
                <div className="text-base box-content caret-black gap-x-[normal] block flex-nowrap leading-[normal] min-h-0 min-w-0 outline-black gap-y-[normal] scroll-auto mt-0 md:text-sm md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:flex-wrap md:leading-5 md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-10 md:scroll-m-0 md:scroll-p-[auto]">
                  {projectTechnologies.map((tech) => (
                    <div key={tech.id} className="box-content caret-black min-h-0 min-w-0 outline-black scroll-auto md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      <span className="text-black [align-items:normal] bg-transparent box-content caret-black gap-x-[normal] inline shrink justify-normal outline-black gap-y-[normal] scroll-auto text-wrap w-auto p-0 rounded-none md:text-white md:items-center md:aspect-auto md:bg-[oklch(0.205_0_0)] md:box-border md:caret-transparent md:gap-x-2 md:inline-flex md:shrink-0 md:justify-center md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-fit md:border md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:px-3 md:py-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[10px] md:border-solid md:border-[oklab(0.999994_0.0000455678_0.0000200868_/_0.14)]">
                        <img alt={tech.name} src={tech.iconSrc} className="box-content caret-black max-w-none min-h-0 min-w-0 outline-black scroll-auto text-wrap w-auto md:aspect-[auto_16_/_16] md:box-border md:caret-transparent md:max-w-full md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-4 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
                        {tech.name}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <a href="/projects" className="text-neutral-100 items-center box-border caret-transparent gap-x-2 flex justify-center outline-[oklab(0.556_0_0_/_0.5)] gap-y-2 scroll-smooth w-fit mt-0 mx-auto md:mt-20">
        See more projects
        <div className="bg-[oklab(0.999994_0.0000455678_0.0000200868_/_0.05)] box-border caret-transparent h-[25px] outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth w-[25px] border overflow-hidden rounded-[3.35544e+07px] border-solid border-[oklab(0.999994_0.0000455678_0.0000200868_/_0.1)]">
          <div className="box-border caret-transparent flex outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth w-12">
            <span className="box-border caret-transparent flex h-6 outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth w-6">
              <img src="https://c.animaapp.com/mfbwn9s8eMdF5x/assets/icon-21.svg" alt="Icon" className="box-border caret-transparent h-3.5 outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth w-3.5 m-auto" />
            </span>
            <span className="box-border caret-transparent flex h-6 outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth w-6">
              <img src="https://c.animaapp.com/mfbwn9s8eMdF5x/assets/icon-21.svg" alt="Icon" className="box-border caret-transparent h-3.5 outline-[oklab(0.556_0_0_/_0.5)] scroll-smooth w-3.5 m-auto" />
            </span>
          </div>
        </div>
      </a>
      
      <span className="static [align-items:normal] box-content caret-black inline h-auto justify-normal opacity-100 outline-black scroll-auto w-auto z-auto rounded-none left-auto top-auto md:fixed md:items-center md:aspect-auto md:backdrop-blur md:box-border md:caret-transparent md:flex md:h-[11px] md:justify-center md:opacity-0 md:outline-[oklab(0.556_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:scroll-smooth md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[11px] md:z-50 md:border md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[3.35544e+07px] md:border-solid md:border-[oklab(0.999994_0.0000455678_0.0000200868_/_0.25)] md:left-0 md:top-0"></span>
    </section>
  );
}
